---
abstract: 'implementation for perldoc-search'
author:
  - 'Josh Jore <jjore@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Perldoc-Search
requires:
  Test::More: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-Perldoc-Search
  homepage: http://search.cpan.org/dist/App-Perldoc-Search
  repository: git://github.com/jbenjore/app-perldoc-search.git
version: 0.08
